In [1]:
import numpy as np
import pandas as pd

In [2]:
li_data = pd.read_csv('output_li.csv')
li_data.head()
li_data.info()
li_data.shape

li_data.dropna(inplace=True)
print(li_data.isna().sum())


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 23 columns):
 #   Column                            Non-Null Count  Dtype 
---  ------                            --------------  ----- 
 0   li_premium                        42 non-null     int64 
 1   satisfaction_lv                   42 non-null     int64 
 2   freq_of_use                       42 non-null     int64 
 3   li_prem_adv_over_rest             42 non-null     object
 4   li_prem_adv_over_rest_bin         42 non-null     int64 
 5   inmail_effectiveness              42 non-null     int64 
 6   applicant_insights_effectiveness  42 non-null     int64 
 7   linkedin_learning_effectiveness   42 non-null     int64 
 8   profile_insights_effectiveness    42 non-null     int64 
 9   pre_services                      42 non-null     object
 10  Applicant insights                42 non-null     int64 
 11  InMail                            42 non-null     int64 
 12  Linkedin Learning       

In [21]:
li_data.shape

(42, 23)

In [13]:
def chi_sq(df, col1,col2):
    contingency_table = pd.crosstab(df[col1], 
                                df[col2])
    # Perform chi-square test
    chi2, p_value, dof, expected = chi2_contingency(contingency_table)
    # Print the results
    print(f"Chi-square statistic: {chi2}")
    print(f"P-value: {p_value}")
    print(f"Degrees of freedom: {dof}")
    print("Expected frequencies:")
    print(expected)

Null Hypothesis (H0): There is no association between user satisfaction and effectiveness of applicant insights.

Alternative Hypothesis (H1): There is an association between user satisfaction and effectiveness of applicant insights.

alpha = 0.1

In [19]:
appl_insights = li_data[['li_premium','satisfaction_lv','Applicant insights','applicant_insights_effectiveness']]

#premium users who are aware of said feature
condition1 = appl_insights['li_premium'] == 1
condition2 = appl_insights['Applicant insights'] == 1 

aware_premium_users = appl_insights[condition1 & condition2]

print('Feature: Applicant insights')
print(aware_premium_users.shape,'\n')


chi_sq(aware_premium_users, 'satisfaction_lv', 'applicant_insights_effectiveness')


Feature: Applicant insights
(20, 4) 

Chi-square statistic: 23.544973544973544
P-value: 0.09992456068387973
Degrees of freedom: 16
Expected frequencies:
[[1.2  0.4  1.4  0.2  0.8 ]
 [2.7  0.9  3.15 0.45 1.8 ]
 [0.9  0.3  1.05 0.15 0.6 ]
 [0.9  0.3  1.05 0.15 0.6 ]
 [0.3  0.1  0.35 0.05 0.2 ]]


The p-value is 0.099, which is slightly below the 0.1 threshold. With alpha of 0.1, we would conclude that there is a statistically significant association between the two.

In [20]:
inmail = li_data[['li_premium','satisfaction_lv','InMail','inmail_effectiveness']]

#premium users who are aware of said feature
condition1 = inmail['li_premium'] == 1
condition2 = inmail['InMail'] == 1 

aware_premium_users = inmail[condition1 & condition2]

print('Feature: InMail')
print(aware_premium_users.shape,'\n')


chi_sq(aware_premium_users, 'satisfaction_lv', 'inmail_effectiveness')


Feature: InMail
(20, 4) 

Chi-square statistic: 10.509259259259258
P-value: 0.571375461024165
Degrees of freedom: 12
Expected frequencies:
[[0.8  0.6  0.6  0.8  1.2 ]
 [1.8  1.35 1.35 1.8  2.7 ]
 [0.6  0.45 0.45 0.6  0.9 ]
 [0.8  0.6  0.6  0.8  1.2 ]]


In [23]:
learning = li_data[['li_premium','satisfaction_lv','Linkedin Learning','linkedin_learning_effectiveness']]

#premium users who are aware of said feature
condition1 = learning['li_premium'] == 1
condition2 = learning['Linkedin Learning'] == 1 

aware_premium_users = learning[condition1 & condition2]

print('Feature: Linkedin Learning')
print(aware_premium_users.shape,'\n')


chi_sq(aware_premium_users, 'satisfaction_lv', 'linkedin_learning_effectiveness')

Feature: Linkedin Learning
(10, 4) 

Chi-square statistic: 12.222222222222221
P-value: 0.27045931145720786
Degrees of freedom: 10
Expected frequencies:
[[0.1 0.3 0.1 0.1 0.2 0.2]
 [0.6 1.8 0.6 0.6 1.2 1.2]
 [0.3 0.9 0.3 0.3 0.6 0.6]]


In [25]:
prof_ins = li_data[['li_premium','satisfaction_lv','Profile insights','profile_insights_effectiveness']]

#premium users who are aware of said feature
condition1 = prof_ins['li_premium'] == 1
condition2 = prof_ins['Profile insights'] == 1 

aware_premium_users = prof_ins[condition1 & condition2]

print('Feature: Profile insights')
print(aware_premium_users.shape,'\n')


chi_sq(aware_premium_users, 'satisfaction_lv', 'profile_insights_effectiveness')

Feature: Profile insights
(15, 4) 

Chi-square statistic: 18.142857142857142
P-value: 0.315598174354914
Degrees of freedom: 16
Expected frequencies:
[[1.33333333 0.26666667 0.8        0.8        0.8       ]
 [2.33333333 0.46666667 1.4        1.4        1.4       ]
 [0.33333333 0.06666667 0.2        0.2        0.2       ]
 [0.66666667 0.13333333 0.4        0.4        0.4       ]
 [0.33333333 0.06666667 0.2        0.2        0.2       ]]
